language: scala

jdk: oraclejdk8

scala:
   - 2.12.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
   - sbt ++$TRAVIS_SCALA_VERSION test
   - sbt ++$TRAVIS_SCALA_VERSION scalastyle
   - sbt clean coverage test
   - sbt coverageReport
   - sbt coverageAggregate

after_succes:
   - sbt coveralls

notifications:
  email: false